[command]
static = false

[sysimg]
incremental = false
filter_stdlibs = false

[sysimg.precompile]
execution_file = ["test/runtests.jl"]

[application]
incremental = false
filter_stdlibs = false

[application.precompile]
execution_file = ["test/runtests.jl"]
