name = "Kata"
uuid = "f31b65f3-1827-4085-acd2-3666a98a32d9"
authors = ["KwatMDPhD"]
version = "0.3.0-DEV"

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Pkg", "Test"]
