name = "NAME"
uuid = "e8386f20-3e60-497e-8358-52c6451f91c7"
authors = ["AUTHOR"]
version = "1.0.0-DEV"

[deps]

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
